### ISSUE TITLE
Request use of Minecraft installer or to uninstall outdated Java versions

### ISSUE THREAD

**Issue by Kumasasa** [Synchunk/Arisa#18]
https://bugs.mojang.com/browse/MC-80382 has Java: **1.8.0_45** but was flagged with *Your Java version is out of date!*

**Comment by Synchunk** [comment]
The bot gets the Java version from the crash report (`Java Version: 1.6.0_20, Sun Microsystems Inc.`), not from the launcher output (`Java: 1.8.0_45 (by Oracle Corporation)`).
I have no idea why the launcher started the game with Java 1.6 while the launcher itself uses Java 1.8.

I'm not sure which one is the better solution:
* adding instructions telling people to uninstall all outdated versions (as in `#minecrafthelp`)
* checking the **latest** Java version from game **or** launcher, not only the Java version the game uses

What do you think?

**Comment by stupid3700** [comment]
@Synchunk It seems logical to get the Java version from the crash report, and so should remain that way.
Out of the two options, the former would be the better option, perhaps using the same instructions as the Vox factoid to completely reinstall Java.

**Comment by Kumasasa** [comment]
Oops, didn't completely read the snapshot. 
In fact the Launcher's Java version is quite irrelevant, the game's version is more important - so the bot was absolutely correct about the version.

Wouldn't it be an option instead of directing the users to manually uninstall Java to direct them to download & install the Minecraft Installer from https://minecraft.net/download (in case OS is Windows) ?
Uninstalling Java may break other software on user's computers.

**Comment by Synchunk** [comment]
Sounds like a good idea!
