### ISSUE TITLE
Prioritise checks on issues

### ISSUE THREAD

**Issue by stupid3700** [Synchunk/Arisa#19]
Prioritise checks so that those of less importance, those of less relevance or those that are less likely to give an accurate comment/resolution don't run if a check of higher priority has run.

As an example (following implementation of #5), if a duplicate was detected, and the report also contained an outdated Java version, there would be little point in resolving it as a duplicate and commenting regarding the duplicate issue, then commenting again for the outdated Java version (which I believe asks the user to report after updating their Java).

**Comment by Synchunk** [comment]
Fixed in v1.0.
