### ISSUE TITLE
Be more lenient on issue description length check

### ISSUE THREAD

**Issue by stupid3700** [Synchunk/Arisa#20]
May need to make Arisa more lenient on its length check after it closed an issue identified as valid by @Mustek (although noting the description isn't very long or descriptive).
Reference: [MC-80658](https://bugs.mojang.com/browse/MC-80658)

**Comment by Kumasasa** [comment]
May also apply to [MCCE-240](https://bugs.mojang.com/browse/MCCE-240)

**Comment by stupid3700** [comment]
@Kumasasa Description was blank on that issue when it was resolved, and was updated afterwards.

**Comment by Synchunk** [comment]
@Kumasasa Moved that to #21.

**Comment by Kumasasa** [comment]
@stupid3700: sry, didn't see that.
@Synchunk: #21 would be a good feature

**Comment by Synchunk** [comment]
The bot could trash [completely empty issues](https://bugs.mojang.com/browse/TRASH-9303) (as they're usually spam) while [commenting](https://github.com/Synchunk/Arisa/blob/75a410e4484533983d590369b083a33fcaf345b6/responses/awaiting_response/generic) on issues which [are incomplete but not completely empty](https://bugs.mojang.com/browse/MC-80658) and resolving them as *[Awaiting Response](4)*. I definitely want to ask @Dinnerbone's opinion before deleting issues though and I'm not sure whether deleting or resolving completely empty issues is the better solution. What do you think about that?
