### ISSUE TITLE
"Incomplete without crash report" should be added to crash tickets

### ISSUE THREAD

**Issue by Kumasasa** [Synchunk/Arisa#23]
When users experience a crash and hit on "Report to Mojang" the environment field of the ticket is filled out

> OS: Windows 8.1 (ver 6.3, arch amd64)
> Java: 1.8.0_25 (by Oracle Corporation)
Launcher: Minecraft Launcher 1.6.11 (bootstrap 100)
Minecraft: 1.8.6 (updated Mon May 25 12:31:19 CEST 2015)

but users usually leave the description field intact 

> Put the summary of the bug you're having here
What I expected to happen was...:
Describe what you thought should happen here
What actually happened was...:
Describe what happened here
Steps to Reproduce:
1. Put a step by step guide on how to trigger the bug here
2. ...
3. ...

but also usually fail to attach the crash report.

The default description field is detected and the ticket resolved with 

> This ticket is incomplete. Please review the guidelines before reporting issues.
For technical support please use the Mojang Support Center.
— This action was performed automatically. If you believe this was done erroneously, please raise an issue.

but a better action would be not only to detect the default description field but also scan through the environment field, detect there the presence of 

> OS: *
> Java: *
Launcher: *
Minecraft: *

and resolve the ticket with

> Incomplete without a crash report from (minecraft/crash-reports/crash-<DATE>-client.txt). Please attach it so that we can diagnose your issue.

Example: https://bugs.mojang.com/browse/MC-80962

**Comment by Kumasasa** [comment]
... and of course tickets should be reopened if the user comments in any way: Either file is attached or a somewhat lengthy comment (> 500 bytes) is put to the ticket

**Comment by Synchunk** [comment]
Even better than detecting launcher crashes: reading the game version from the *Environment* field and checking if it's outdated: [MC-81138](https://bugs.mojang.com/browse/MC-81138)
