### ISSUE TITLE
Incorrect "unreleased versions" detection.

### ISSUE THREAD

**Issue by Dinnerbone** [Synchunk/Arisa#24]
On the issue [MC-81015](https://bugs.mojang.com/browse/MC-81015), a user reported an issue for 1.8.7. This had been marked Released for approximately 10 minutes before the issue was opened. The bot warned the user about unreleased versions and downgraded it to 1.8.6.

**Comment by Plazmaz** [comment]
Confirmed, also, a bug report on a fix for bug reports created a new bug report.

**Comment by Plazmaz** [comment]
Also appears to continuously reset the version regardless of administrator or user actions
